/** Curated Indian government startup schemes with official portals.
 *  `stages` drives the "recommended for your stage" filter on the student dashboard.
 *  When the n8n pipeline runs, MentorAI's output can replace/augment this list. */
export const SCHEMES = [
  {
    name: 'Startup India Seed Fund Scheme (SISFS)',
    org: 'DPIIT · Government of India',
    desc: 'Up to ₹20L grant for proof-of-concept/prototype and up to ₹50L for market entry, via approved incubators.',
    tags: ['Funding', 'Seed'],
    stages: ['Idea', 'Validation', 'MVP'],
    url: 'https://seedfund.startupindia.gov.in/',
  },
  {
    name: 'DPIIT Startup Recognition',
    org: 'Startup India',
    desc: 'Official recognition unlocking tax exemptions, self-certification, and eligibility for most schemes below.',
    tags: ['Recognition'],
    stages: ['Idea', 'Validation', 'MVP', 'Launch', 'Growth', 'Fundraising'],
    url: 'https://www.startupindia.gov.in/',
  },
  {
    name: 'Atal Innovation Mission — Incubation',
    org: 'NITI Aayog',
    desc: 'Support, mentorship and grants through Atal Incubation Centres for early-stage innovators.',
    tags: ['Incubation', 'Grant'],
    stages: ['Idea', 'Validation', 'MVP'],
    url: 'https://aim.gov.in/',
  },
  {
    name: 'NIDHI',
    org: 'DST · Government of India',
    desc: 'Umbrella of seed support (NIDHI-SSS), incubation and accelerator programs for tech startups.',
    tags: ['Funding', 'Incubation'],
    stages: ['Idea', 'Validation', 'MVP'],
    url: 'https://nidhi.dst.gov.in/',
  },
  {
    name: 'Credit Guarantee Scheme for Startups (CGSS)',
    org: 'DPIIT · NCGTC',
    desc: 'Collateral-free loan guarantee for DPIIT-recognised startups.',
    tags: ['Loan', 'Guarantee'],
    stages: ['MVP', 'Launch', 'Growth'],
    url: 'https://www.startupindia.gov.in/',
  },
  {
    name: 'SAMRIDH Scheme',
    org: 'MeitY · Government of India',
    desc: 'Up to ₹40L funding plus acceleration for existing software product startups to scale.',
    tags: ['Funding', 'Software'],
    stages: ['MVP', 'Launch', 'Growth'],
    url: 'https://samridh.meity.gov.in/',
  },
  {
    name: 'Pradhan Mantri MUDRA Yojana (PMMY)',
    org: 'MUDRA · Government of India',
    desc: 'Micro-loans up to ₹10L (Shishu / Kishor / Tarun) for small businesses — no collateral.',
    tags: ['Loan'],
    stages: ['Launch', 'Growth'],
    url: 'https://www.mudra.org.in/',
  },
  {
    name: 'Stand-Up India',
    org: 'SIDBI · Government of India',
    desc: 'Bank loans ₹10L–₹1Cr for women and SC/ST entrepreneurs setting up greenfield ventures.',
    tags: ['Loan', 'Women', 'SC/ST'],
    stages: ['Launch', 'Growth'],
    url: 'https://www.standupmitra.in/',
  },
  {
    name: 'SIDBI Fund of Funds for Startups (FFS)',
    org: 'SIDBI · Government of India',
    desc: 'Indirect equity funding into startups through SEBI-registered Alternative Investment Funds.',
    tags: ['Funding', 'Equity'],
    stages: ['Growth', 'Fundraising'],
    url: 'https://www.sidbi.in/',
  },
  {
    name: 'Udyam (MSME) Registration',
    org: 'Ministry of MSME',
    desc: 'Free MSME registration unlocking subsidies, priority lending, and government tender benefits.',
    tags: ['Recognition', 'MSME'],
    stages: ['Idea', 'Validation', 'MVP', 'Launch', 'Growth', 'Fundraising'],
    url: 'https://udyamregistration.gov.in/',
  },
  {
    name: 'Women Entrepreneurship Platform (WEP)',
    org: 'NITI Aayog',
    desc: 'Funding access, mentorship, and incubation support for women-led startups.',
    tags: ['Women', 'Support'],
    stages: ['Idea', 'Validation', 'MVP', 'Launch', 'Growth'],
    url: 'https://wep.gov.in/',
  },
]
